type machine_type =
    | IMAGE_FILE_MACHINE_UNKNOWN
    | IMAGE_FILE_MACHINE_AM33
    | IMAGE_FILE_MACHINE_AMD64
    | IMAGE_FILE_MACHINE_ARM
    | IMAGE_FILE_MACHINE_ARMNT
    | IMAGE_FILE_MACHINE_ARM64
    | IMAGE_FILE_MACHINE_EBC
    | IMAGE_FILE_MACHINE_I386
    | IMAGE_FILE_MACHINE_IA64
    | IMAGE_FILE_MACHINE_M32R
    | IMAGE_FILE_MACHINE_MIPS16
    | IMAGE_FILE_MACHINE_MIPSFPU
    | IMAGE_FILE_MACHINE_MIPSFPU16
    | IMAGE_FILE_MACHINE_POWERPC
    | IMAGE_FILE_MACHINE_POWERPCFP
    | IMAGE_FILE_MACHINE_R4000
    | IMAGE_FILE_MACHINE_SH3
    | IMAGE_FILE_MACHINE_SH3DSP
    | IMAGE_FILE_MACHINE_SH4
    | IMAGE_FILE_MACHINE_SH5
    | IMAGE_FILE_MACHINE_THUMB
    | IMAGE_FILE_MACHINE_WCEMIPSV2
    | UNKNOWN of int

let get_machine_type =
  function
  | 0x0 -> IMAGE_FILE_MACHINE_UNKNOWN
  | 0x1d3 -> IMAGE_FILE_MACHINE_AM33
  | 0x8664 -> IMAGE_FILE_MACHINE_AMD64
  | 0x1c0 -> IMAGE_FILE_MACHINE_ARM
  | 0x1c4 -> IMAGE_FILE_MACHINE_ARMNT
  | 0xaa64 -> IMAGE_FILE_MACHINE_ARM64
  | 0xebc -> IMAGE_FILE_MACHINE_EBC
  | 0x14c -> IMAGE_FILE_MACHINE_I386
  | 0x200 -> IMAGE_FILE_MACHINE_IA64
  | 0x9041 -> IMAGE_FILE_MACHINE_M32R
  | 0x266 -> IMAGE_FILE_MACHINE_MIPS16
  | 0x366 -> IMAGE_FILE_MACHINE_MIPSFPU
  | 0x466 -> IMAGE_FILE_MACHINE_MIPSFPU16
  | 0x1f0 -> IMAGE_FILE_MACHINE_POWERPC
  | 0x1f1 -> IMAGE_FILE_MACHINE_POWERPCFP
  | 0x166 -> IMAGE_FILE_MACHINE_R4000
  | 0x1a2 -> IMAGE_FILE_MACHINE_SH3
  | 0x1a3 -> IMAGE_FILE_MACHINE_SH3DSP
  | 0x1a6 -> IMAGE_FILE_MACHINE_SH4
  | 0x1a8 -> IMAGE_FILE_MACHINE_SH5
  | 0x1c2 -> IMAGE_FILE_MACHINE_THUMB
  | 0x169 -> IMAGE_FILE_MACHINE_WCEMIPSV2
  | x -> UNKNOWN x

let machine_type_to_int =
  function
  | IMAGE_FILE_MACHINE_UNKNOWN -> 0x0
  | IMAGE_FILE_MACHINE_AM33 -> 0x1d3
  | IMAGE_FILE_MACHINE_AMD64 -> 0x8664
  | IMAGE_FILE_MACHINE_ARM -> 0x1c0
  | IMAGE_FILE_MACHINE_ARMNT -> 0x1c4
  | IMAGE_FILE_MACHINE_ARM64 -> 0xaa64
  | IMAGE_FILE_MACHINE_EBC -> 0xebc
  | IMAGE_FILE_MACHINE_I386 -> 0x14c
  | IMAGE_FILE_MACHINE_IA64 -> 0x200
  | IMAGE_FILE_MACHINE_M32R -> 0x9041
  | IMAGE_FILE_MACHINE_MIPS16 -> 0x266
  | IMAGE_FILE_MACHINE_MIPSFPU -> 0x366
  | IMAGE_FILE_MACHINE_MIPSFPU16 -> 0x466
  | IMAGE_FILE_MACHINE_POWERPC -> 0x1f0
  | IMAGE_FILE_MACHINE_POWERPCFP -> 0x1f1
  | IMAGE_FILE_MACHINE_R4000 -> 0x166
  | IMAGE_FILE_MACHINE_SH3 -> 0x1a2
  | IMAGE_FILE_MACHINE_SH3DSP -> 0x1a3
  | IMAGE_FILE_MACHINE_SH4 -> 0x1a6
  | IMAGE_FILE_MACHINE_SH5 -> 0x1a8
  | IMAGE_FILE_MACHINE_THUMB -> 0x1c2
  | IMAGE_FILE_MACHINE_WCEMIPSV2 -> 0x169
  | UNKNOWN x -> x

let machine_type_to_string =
  function
  | IMAGE_FILE_MACHINE_UNKNOWN -> "IMAGE_FILE_MACHINE_UNKNOWN"
  | IMAGE_FILE_MACHINE_AM33 -> "IMAGE_FILE_MACHINE_AM33"
  | IMAGE_FILE_MACHINE_AMD64 -> "IMAGE_FILE_MACHINE_AMD64"
  | IMAGE_FILE_MACHINE_ARM -> "IMAGE_FILE_MACHINE_ARM"
  | IMAGE_FILE_MACHINE_ARMNT -> "IMAGE_FILE_MACHINE_ARMNT"
  | IMAGE_FILE_MACHINE_ARM64 -> "IMAGE_FILE_MACHINE_ARM64"
  | IMAGE_FILE_MACHINE_EBC -> "IMAGE_FILE_MACHINE_EBC"
  | IMAGE_FILE_MACHINE_I386 -> "IMAGE_FILE_MACHINE_I386"
  | IMAGE_FILE_MACHINE_IA64 -> "IMAGE_FILE_MACHINE_IA64"
  | IMAGE_FILE_MACHINE_M32R -> "IMAGE_FILE_MACHINE_M32R"
  | IMAGE_FILE_MACHINE_MIPS16 -> "IMAGE_FILE_MACHINE_MIPS16"
  | IMAGE_FILE_MACHINE_MIPSFPU -> "IMAGE_FILE_MACHINE_MIPSFPU"
  | IMAGE_FILE_MACHINE_MIPSFPU16 -> "IMAGE_FILE_MACHINE_MIPSFPU16"
  | IMAGE_FILE_MACHINE_POWERPC -> "IMAGE_FILE_MACHINE_POWERPC"
  | IMAGE_FILE_MACHINE_POWERPCFP -> "IMAGE_FILE_MACHINE_POWERPCFP"
  | IMAGE_FILE_MACHINE_R4000 -> "IMAGE_FILE_MACHINE_R4000"
  | IMAGE_FILE_MACHINE_SH3 -> "IMAGE_FILE_MACHINE_SH3"
  | IMAGE_FILE_MACHINE_SH3DSP -> "IMAGE_FILE_MACHINE_SH3DSP"
  | IMAGE_FILE_MACHINE_SH4 -> "IMAGE_FILE_MACHINE_SH4"
  | IMAGE_FILE_MACHINE_SH5 -> "IMAGE_FILE_MACHINE_SH5"
  | IMAGE_FILE_MACHINE_THUMB -> "IMAGE_FILE_MACHINE_THUMB"
  | IMAGE_FILE_MACHINE_WCEMIPSV2 -> "IMAGE_FILE_MACHINE_WCEMIPSV2"
  | UNKNOWN x -> Printf.sprintf "UNKNOWN_MACHINE_TYPE 0x%x" x

